{
  "url": "https://api.github.com/repos/Microsoft/Pyjion/issues/109",
  "repository_url": "https://api.github.com/repos/Microsoft/Pyjion",
  "labels_url": "https://api.github.com/repos/Microsoft/Pyjion/issues/109/labels{/name}",
  "comments_url": "https://api.github.com/repos/Microsoft/Pyjion/issues/109/comments",
  "events_url": "https://api.github.com/repos/Microsoft/Pyjion/issues/109/events",
  "html_url": "https://github.com/Microsoft/Pyjion/pull/109",
  "id": 128921459,
  "number": 109,
  "title": "Classify all known failures",
  "user": {
    "login": "brettcannon",
    "id": 54418,
    "avatar_url": "https://avatars.githubusercontent.com/u/54418?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/brettcannon",
    "html_url": "https://github.com/brettcannon",
    "followers_url": "https://api.github.com/users/brettcannon/followers",
    "following_url": "https://api.github.com/users/brettcannon/following{/other_user}",
    "gists_url": "https://api.github.com/users/brettcannon/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/brettcannon/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/brettcannon/subscriptions",
    "organizations_url": "https://api.github.com/users/brettcannon/orgs",
    "repos_url": "https://api.github.com/users/brettcannon/repos",
    "events_url": "https://api.github.com/users/brettcannon/events{/privacy}",
    "received_events_url": "https://api.github.com/users/brettcannon/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [
    {
      "url": "https://api.github.com/repos/Microsoft/Pyjion/labels/cla-not-required",
      "name": "cla-not-required",
      "color": "009800"
    }
  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "milestone": null,
  "comments": 0,
  "created_at": "2016-01-26T19:42:35Z",
  "updated_at": "2016-01-26T22:51:30Z",
  "closed_at": "2016-01-26T19:42:41Z",
  "pull_request": {
    "url": "https://api.github.com/repos/Microsoft/Pyjion/pulls/109",
    "html_url": "https://github.com/Microsoft/Pyjion/pull/109",
    "diff_url": "https://github.com/Microsoft/Pyjion/pull/109.diff",
    "patch_url": "https://github.com/Microsoft/Pyjion/pull/109.patch"
  },
  "body": "Now all known tests failing a Python test have an associated issue.",
  "closed_by": {
    "login": "brettcannon",
    "id": 54418,
    "avatar_url": "https://avatars.githubusercontent.com/u/54418?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/brettcannon",
    "html_url": "https://github.com/brettcannon",
    "followers_url": "https://api.github.com/users/brettcannon/followers",
    "following_url": "https://api.github.com/users/brettcannon/following{/other_user}",
    "gists_url": "https://api.github.com/users/brettcannon/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/brettcannon/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/brettcannon/subscriptions",
    "organizations_url": "https://api.github.com/users/brettcannon/orgs",
    "repos_url": "https://api.github.com/users/brettcannon/repos",
    "events_url": "https://api.github.com/users/brettcannon/events{/privacy}",
    "received_events_url": "https://api.github.com/users/brettcannon/received_events",
    "type": "User",
    "site_admin": false
  }
}
